### ISSUE TITLE
ff-only merges can't be reverted

### ISSUE THREAD

**Issue by aaronjensen** [kentcdodds/rebase-and-merge#1]
Maybe not the right place for a discussion, but I don't think the goal of this plugin actually enables the best workflow. If you don't have a merge commit, you can't revert it. You have to revert each commit individually or a range, but people won't actually know which commits need to be reverted. A workflow of rebase and then no-ff merge is nice, especially if you're using github protected branches (I hate the "Update branch" button). 

So... I'd love a button that was a replacement for the "Update branch" button that simply rebased instead of merging master back in. I know that wasn't your original goal, but I just wanted to throw in my 2 cents :smile: Thanks!

**Comment by kentcdodds** [comment]
Definitely feel free to fork the project and make your own webtask that does this :-) Cheers!
