### ISSUE TITLE
--depth=50?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/rebase-and-merge#2]
TravisCI clones the repo with the `--depth` argument. I presume this speeds up the clone considerably, though I don't know much about it. Would I be safe to add a `--depth` and make it configurable? The plugin/bookmarklet could probably tell how many commits there are in the PR and send the proper `--depth` but I may be misunderstanding how `--depth` works.

**Comment by SomeKittens** [comment]
`--depth` specifies how many commits to go back.  Not sure about internals here but you shouldn't need any more than the # you're rebasing.

**Comment by kentcdodds** [comment]
So it would probably speed up the git clone right?

**Comment by SomeKittens** [comment]
Oh yes, especially on large repos.
