### ISSUE TITLE
Add rebase, then merge functionality

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/rebase-and-merge#3]

**Comment by jamiebuilds** [comment]
Step 1: Hype
Step 2: Build
Step 3: Profit

:wink:

**Comment by kentcdodds** [comment]
@thejameskyle ?

**Comment by kentcdodds** [comment]
Oh, are you suggesting that this issue indicates that the tool doesn't actually work yet? Because it totally does. This issue is intended to do a rebase and forever push to the branch and then merge. That way GitHub recognizes the merge.
