### ISSUE TITLE
Webtask.io token error?

### ISSUE THREAD

**Issue by jimthedev** [kentcdodds/rebase-and-merge#4]
Hi Kent, 

I used this a week ago and it was working great. Today I tried it and received the following:

```
{"code":404,"message":"unable to resolve jtn to webtask token", req_id: 123456789 }
```

I tried regenerating my GH access token and my bookmarklet just in case I'd introduced a typo somehow but it did not resolve it. I found some previous tweets about this error where folks were speculating that the webtask.io cluster was having problems. 

Have you used this recently?

**Comment by kentcdodds** [comment]
Could be because they've just recently changed their pricing model to make it so free webtasks only work for 30 days :-( Thinking about putting this up on AWS lambda. But my account is suspended for some reason.... You wanna give it a shot? Should be pretty straightforward.

**Comment by martinhbramwell** [comment]
This error appears if you do not specify a valid path.

Try this one for example : 
https://wt-666ohgod666ohgod666ohgod666ohgod-0.run.webtask.io/antidisestablishmentarianism666

**Comment by ggoodman** [comment]
As a note of clarification. We no longer suggest that webtasks would only work for 30 days. That limit was _never actually enforced_ so we removed the language. You can see [on our pricing page](https://webtask.io/pricing) that https://webtask.io is free up to 1 request/second.

**Comment by kentcdodds** [comment]
That's great to hear @ggoodman :+1:
