### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by zspecza** [kentcdodds/rebase-and-merge#6]
Weirdly titled issue, I know. Figured you could use this issue as a place to document alternative services and/or new approaches to getting your script working again.

I read your deprecation notice and wanted to show you this:
##### (_free for open source_, but private repos are **very** expensive)

![](https://remergr.io/img/remergr-example.gif)

AWS Lambda seems like it could work, but perhaps it might be better to see if [IFTTT](https://ifttt.com/) could accommodate this project somehow? Otherwise, Heroku's free tier + NewRelic setup to do an availability check (which has the side-effect of keeping the dyno online)

**Comment by kentcdodds** [comment]
So, this basically does what `rebase-and-merge` is supposed to do but more right? Sounds super! Could you submit a PR to add this to the top of the README?

I've installed the extension, so once you've created the PR, I'll try to merge it with the extension :-)

**Comment by zspecza** [comment]
Kind of, they support a lot more features than just `rebase-and-merge` (like in-browser conflict resolution and the ability to update a branch that's fallen behind `master`, also with the ability to do so via rebase, directly in the browser)

All that being said, this won't do for private projects given their steep price, so I still think a completely free version that just handles the `merge-and-rebase` is a worthwhile endeavour
